# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_checkbox.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(631, 642)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblResultHobiler = QtWidgets.QLabel(self.centralwidget)
        self.lblResultHobiler.setGeometry(QtCore.QRect(70, 280, 181, 131))
        self.lblResultHobiler.setText("")
        self.lblResultHobiler.setObjectName("lblResultHobiler")
        self.btnHobiler1SecilenleriAl = QtWidgets.QPushButton(self.centralwidget)
        self.btnHobiler1SecilenleriAl.setGeometry(QtCore.QRect(100, 220, 121, 41))
        self.btnHobiler1SecilenleriAl.setObjectName("btnHobiler1SecilenleriAl")
        self.groupHobiler = QtWidgets.QGroupBox(self.centralwidget)
        self.groupHobiler.setGeometry(QtCore.QRect(60, 20, 211, 201))
        self.groupHobiler.setObjectName("groupHobiler")
        self.widget = QtWidgets.QWidget(self.groupHobiler)
        self.widget.setGeometry(QtCore.QRect(50, 30, 101, 141))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbSinema = QtWidgets.QCheckBox(self.widget)
        self.cbSinema.setObjectName("cbSinema")
        self.verticalLayout.addWidget(self.cbSinema)
        self.cbKitapOkumak = QtWidgets.QCheckBox(self.widget)
        self.cbKitapOkumak.setObjectName("cbKitapOkumak")
        self.verticalLayout.addWidget(self.cbKitapOkumak)
        self.cbSpor = QtWidgets.QCheckBox(self.widget)
        self.cbSpor.setObjectName("cbSpor")
        self.verticalLayout.addWidget(self.cbSpor)
        self.groupHobiler_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupHobiler_2.setGeometry(QtCore.QRect(380, 20, 211, 201))
        self.groupHobiler_2.setObjectName("groupHobiler_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupHobiler_2)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 30, 107, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbDansEtmek = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbDansEtmek.setObjectName("cbDansEtmek")
        self.verticalLayout_2.addWidget(self.cbDansEtmek)
        self.cbResimYapmak = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbResimYapmak.setObjectName("cbResimYapmak")
        self.verticalLayout_2.addWidget(self.cbResimYapmak)
        self.cbFotografCekmek = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbFotografCekmek.setObjectName("cbFotografCekmek")
        self.verticalLayout_2.addWidget(self.cbFotografCekmek)
        self.btnHobiler2SecilenleriAl = QtWidgets.QPushButton(self.centralwidget)
        self.btnHobiler2SecilenleriAl.setGeometry(QtCore.QRect(410, 220, 121, 41))
        self.btnHobiler2SecilenleriAl.setObjectName("btnHobiler2SecilenleriAl")
        self.lblResultHobiler2 = QtWidgets.QLabel(self.centralwidget)
        self.lblResultHobiler2.setGeometry(QtCore.QRect(390, 270, 181, 131))
        self.lblResultHobiler2.setText("")
        self.lblResultHobiler2.setObjectName("lblResultHobiler2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 631, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnHobiler1SecilenleriAl.setText(_translate("MainWindow", "Seçilenleri Al"))
        self.groupHobiler.setTitle(_translate("MainWindow", "GroupBox"))
        self.cbSinema.setText(_translate("MainWindow", "Sinema"))
        self.cbKitapOkumak.setText(_translate("MainWindow", "Kitap Okumak"))
        self.cbSpor.setText(_translate("MainWindow", "Spor"))
        self.groupHobiler_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.cbDansEtmek.setText(_translate("MainWindow", "Dans Etmek"))
        self.cbResimYapmak.setText(_translate("MainWindow", "Resim Yapmak"))
        self.cbFotografCekmek.setText(_translate("MainWindow", "Fotoğraf Çekmek"))
        self.btnHobiler2SecilenleriAl.setText(_translate("MainWindow", "Seçilenleri Al"))
