<<<<<<< HEAD
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_radiobuttonform.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 445)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblUlke = QtWidgets.QLabel(self.centralwidget)
        self.lblUlke.setGeometry(QtCore.QRect(30, 220, 101, 61))
        self.lblUlke.setText("")
        self.lblUlke.setObjectName("lblUlke")
        self.lblEgitim = QtWidgets.QLabel(self.centralwidget)
        self.lblEgitim.setGeometry(QtCore.QRect(250, 210, 101, 61))
        self.lblEgitim.setText("")
        self.lblEgitim.setObjectName("lblEgitim")
        self.btnUlke = QtWidgets.QPushButton(self.centralwidget)
        self.btnUlke.setGeometry(QtCore.QRect(40, 290, 75, 23))
        self.btnUlke.setObjectName("btnUlke")
        self.btnEgitim = QtWidgets.QPushButton(self.centralwidget)
        self.btnEgitim.setGeometry(QtCore.QRect(250, 290, 75, 23))
        self.btnEgitim.setObjectName("btnEgitim")
        self.groupBoxUlke = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxUlke.setGeometry(QtCore.QRect(20, 30, 151, 161))
        self.groupBoxUlke.setObjectName("groupBoxUlke")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBoxUlke)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 131, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayoutUlke = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayoutUlke.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutUlke.setObjectName("gridLayoutUlke")
        self.radioAzerbaycan = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioAzerbaycan.setObjectName("radioAzerbaycan")
        self.gridLayoutUlke.addWidget(self.radioAzerbaycan, 4, 0, 1, 1)
        self.radioAlmanya = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioAlmanya.setObjectName("radioAlmanya")
        self.gridLayoutUlke.addWidget(self.radioAlmanya, 2, 0, 1, 1)
        self.radioYunanistan = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioYunanistan.setObjectName("radioYunanistan")
        self.gridLayoutUlke.addWidget(self.radioYunanistan, 3, 0, 1, 1)
        self.radioTurkiye = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioTurkiye.setObjectName("radioTurkiye")
        self.gridLayoutUlke.addWidget(self.radioTurkiye, 1, 0, 1, 1)
        self.groupBoxEgitim = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxEgitim.setGeometry(QtCore.QRect(220, 30, 171, 171))
        self.groupBoxEgitim.setObjectName("groupBoxEgitim")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBoxEgitim)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 131, 121))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayoutEgitim = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayoutEgitim.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutEgitim.setObjectName("gridLayoutEgitim")
        self.radioLise = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioLise.setObjectName("radioLise")
        self.gridLayoutEgitim.addWidget(self.radioLise, 1, 0, 1, 1)
        self.radioUniversite = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioUniversite.setObjectName("radioUniversite")
        self.gridLayoutEgitim.addWidget(self.radioUniversite, 2, 0, 1, 1)
        self.radioIlkokul = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioIlkokul.setObjectName("radioIlkokul")
        self.gridLayoutEgitim.addWidget(self.radioIlkokul, 0, 0, 1, 1)
        self.radioYuksekLisans = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioYuksekLisans.setObjectName("radioYuksekLisans")
        self.gridLayoutEgitim.addWidget(self.radioYuksekLisans, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnUlke.setText(_translate("MainWindow", "Ülke Seçimi"))
        self.btnEgitim.setText(_translate("MainWindow", "Egitim Seçimi"))
        self.groupBoxUlke.setTitle(_translate("MainWindow", "GroupBox"))
        self.radioAzerbaycan.setText(_translate("MainWindow", "Azerbaycan"))
        self.radioAlmanya.setText(_translate("MainWindow", "Almanya"))
        self.radioYunanistan.setText(_translate("MainWindow", "Yunanistan"))
        self.radioTurkiye.setText(_translate("MainWindow", "Türkiye"))
        self.groupBoxEgitim.setTitle(_translate("MainWindow", "GroupBox"))
        self.radioLise.setText(_translate("MainWindow", "Lise"))
        self.radioUniversite.setText(_translate("MainWindow", "Üniversite"))
        self.radioIlkokul.setText(_translate("MainWindow", "İlkokul"))
        self.radioYuksekLisans.setText(_translate("MainWindow", "Yüksek Lisans"))
=======
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_radiobuttonform.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 445)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblUlke = QtWidgets.QLabel(self.centralwidget)
        self.lblUlke.setGeometry(QtCore.QRect(30, 220, 101, 61))
        self.lblUlke.setText("")
        self.lblUlke.setObjectName("lblUlke")
        self.lblEgitim = QtWidgets.QLabel(self.centralwidget)
        self.lblEgitim.setGeometry(QtCore.QRect(250, 210, 101, 61))
        self.lblEgitim.setText("")
        self.lblEgitim.setObjectName("lblEgitim")
        self.btnUlke = QtWidgets.QPushButton(self.centralwidget)
        self.btnUlke.setGeometry(QtCore.QRect(40, 290, 75, 23))
        self.btnUlke.setObjectName("btnUlke")
        self.btnEgitim = QtWidgets.QPushButton(self.centralwidget)
        self.btnEgitim.setGeometry(QtCore.QRect(250, 290, 75, 23))
        self.btnEgitim.setObjectName("btnEgitim")
        self.groupBoxUlke = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxUlke.setGeometry(QtCore.QRect(20, 30, 151, 161))
        self.groupBoxUlke.setObjectName("groupBoxUlke")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBoxUlke)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 131, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayoutUlke = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayoutUlke.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutUlke.setObjectName("gridLayoutUlke")
        self.radioAzerbaycan = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioAzerbaycan.setObjectName("radioAzerbaycan")
        self.gridLayoutUlke.addWidget(self.radioAzerbaycan, 4, 0, 1, 1)
        self.radioAlmanya = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioAlmanya.setObjectName("radioAlmanya")
        self.gridLayoutUlke.addWidget(self.radioAlmanya, 2, 0, 1, 1)
        self.radioYunanistan = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioYunanistan.setObjectName("radioYunanistan")
        self.gridLayoutUlke.addWidget(self.radioYunanistan, 3, 0, 1, 1)
        self.radioTurkiye = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioTurkiye.setObjectName("radioTurkiye")
        self.gridLayoutUlke.addWidget(self.radioTurkiye, 1, 0, 1, 1)
        self.groupBoxEgitim = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxEgitim.setGeometry(QtCore.QRect(220, 30, 171, 171))
        self.groupBoxEgitim.setObjectName("groupBoxEgitim")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBoxEgitim)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 131, 121))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayoutEgitim = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayoutEgitim.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutEgitim.setObjectName("gridLayoutEgitim")
        self.radioLise = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioLise.setObjectName("radioLise")
        self.gridLayoutEgitim.addWidget(self.radioLise, 1, 0, 1, 1)
        self.radioUniversite = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioUniversite.setObjectName("radioUniversite")
        self.gridLayoutEgitim.addWidget(self.radioUniversite, 2, 0, 1, 1)
        self.radioIlkokul = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioIlkokul.setObjectName("radioIlkokul")
        self.gridLayoutEgitim.addWidget(self.radioIlkokul, 0, 0, 1, 1)
        self.radioYuksekLisans = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioYuksekLisans.setObjectName("radioYuksekLisans")
        self.gridLayoutEgitim.addWidget(self.radioYuksekLisans, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnUlke.setText(_translate("MainWindow", "Ülke Seçimi"))
        self.btnEgitim.setText(_translate("MainWindow", "Egitim Seçimi"))
        self.groupBoxUlke.setTitle(_translate("MainWindow", "GroupBox"))
        self.radioAzerbaycan.setText(_translate("MainWindow", "Azerbaycan"))
        self.radioAlmanya.setText(_translate("MainWindow", "Almanya"))
        self.radioYunanistan.setText(_translate("MainWindow", "Yunanistan"))
        self.radioTurkiye.setText(_translate("MainWindow", "Türkiye"))
        self.groupBoxEgitim.setTitle(_translate("MainWindow", "GroupBox"))
        self.radioLise.setText(_translate("MainWindow", "Lise"))
        self.radioUniversite.setText(_translate("MainWindow", "Üniversite"))
        self.radioIlkokul.setText(_translate("MainWindow", "İlkokul"))
        self.radioYuksekLisans.setText(_translate("MainWindow", "Yüksek Lisans"))
>>>>>>> 1a46586db7801035ec8faf8e3daad10a30c9983d
